patchelf.1

--print-soname
--set-soname
--remove-rpath

Document three missing commands in manpage

---

configure.ac

It would be nice to fix them in parallel but I lack the time.

Make tests run in serial as they break in parallel

---

README

It is lacking info on how to run the tests

added compillation steps on README

---

.travis.yml

This should make it easier to validate pull requests.
Test build on my fork: https://travis-ci.com/lkollar/patchelf/builds/117626113

Add .travis.yml to enable CI

---

patchelf.1
src/patchelf.cc

Commit 936bae418b77ee9e06a93cd3cd444f4204446973 added support to handle
several files at once, but forgot to update the man and help output to
describe it.
Fixes: 936bae418b77ee9e06a93cd3cd444f4204446973

Update doc to describe multiple filename args allowed

---

src/patchelf.cc
tests/Makefile.am
tests/force-rpath.sh

Fixes #94
Produces expected results with [my test script](https://github.com/NixOS/patchelf/issues/94#issuecomment-338183814).

Consistently use --force-rpath

---

configure.ac
src/Makefile.am
src/patchelf.cc
tests/Makefile.am
tests/plain-needed.sh

Some test code I added as I was testing to see if the memory leak from #67 was still there.

Add libasan build option and test print-needed

---

src/patchelf.cc

This sets the versym entry for a given symbol to 1.
This is one way of fixing something like https://github.com/NixOS/nixpkgs/pull/86078
More sophisticated manipulation of versions would obviously be useful, but the interface should be discussed before it's implemented.

add --clear-symbol-version

---

.travis.yml

Draft PR to make CI run, per request from @Mic92 :)

replace language:nix

---

src/patchelf.cc
tests/Makefile.am
tests/no-gnu-hash.sh

With regression test!
Fixes https://github.com/NixOS/patchelf/issues/287

fix binaries without .gnu.hash section

---

tests/Makefile.am
tests/basic-flags.sh

let's start with the easy targets from coverage reports

increase test coverage

---

.github/workflows/ci.yml
.github/workflows/publish.yml

fixes https://github.com/NixOS/patchelf/issues/212

Automatic release tarball upload

---

src/patchelf.cc

the function is still quite large but hopefully now a bit easier to follow

make modify rpath function smaller

---

src/patchelf.cc

Signed-off-by: zhangwenlong <zhangwenlong@loongson.cn>
Thank you!

support loongarch for patchelf

---

.github/workflows/publish.yml

ci: fix bz2 tarball upload

---

.github/workflows/ci.yml
src/patchelf.cc

fixes https://github.com/NixOS/patchelf/issues/342

add missing <optional> include

---

flake.nix

This makes it easier for packager and fixes https://github.com/NixOS/patchelf/issues/345

make version in tarball more predictable

---

.github/workflows/ci.yml
tests/endianness.sh

As requested in https://github.com/NixOS/patchelf/pull/353

ci: test out-of-tree build

---

patchelf.1

Document --print-needed

---

patchelf.1

man/patchelf: bump date

---

src/elf.h

update vendored elf file

---

src/elf.h

Update elf.h based on [Glibc](https://sourceware.org/git/glibc.git).

Update elf.h based on Glibc

---

COPYING

... to match https://www.gnu.org/licenses/gpl-3.0.txt

COPYING: change http to https

---

src/patchelf.cc

fix compilation with GCC7

---

src/elf.h

glibc: commit: 6f962278e24bdf5cb5f310c5a17add41da95407c

elf.h: Update `RISC-V` relocations

---

tests/set-interpreter-same.sh

fix shellcheck
